server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

      routes:
        # Serviço de Crédito
        - id: credit-service
          uri: http://ms-service-credit:8081
          predicates:
            - Path=/api/credit/**

        # Serviço de Forecast
        - id: forecast-service
          uri: http://ms-service-forecast:8082
          predicates:
            - Path=/api/forecast/**