server:
  port: 8080   # porta onde o gateway vai escutar

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        # Rota para o serviço de crédito
        - id: credit-service
          uri: http://ms-service-credit:8081   # nome do container no Docker
          predicates:
            - Path=/api/credit/**

        # Rota para o serviço de forecasting
        - id: forecast-service
          uri: http://ms-service-forecast:8082
          predicates:
            - Path=/api/forecast/**